<?php
$rawData = <<<'EOD'
279	Aciclovir  Antiviral Topical	"Aciclovir 5 % w/w Cream\n"	Five times daily at approximately four hourly intervals omitting the night time application.
117	Acne combination: Trimethoprim and Adapalene	Acne : Trimethoprim and Adapalene	"Trimethoprim 200mg every 12 hours for 1 month then 300mg every 12 hours for 3 months\n\nAdapalene 0.1% Benzoyl Peroxide 2.5% gel (Epiduo) Apply twice weekly to affected area to start and slowly increase frequency as tolerated.Review after 3 months.\n\nTo continue during and after oral antibiotic to prevent recurrence. get expert opinion if no improvement "
120	Acne Duac	Acne 	"Clindamycin/ Benzoyl peroxide 10 mg/+ 50 mg/ Gel (Duac)\n\nApply twice weekly to affected area to start and slowly increase frequency as tolerated. Once tolerated it can be applied every 24 hours. Review and limit use to 3 months if no improvement get expert opinion "
182	Acnecide/Benzoyl peroxide Acne	Acnecide/Benzoyl peroxide 	Acnecide/Benzoyl peroxide 5%. Apply in a thin layer to the affected areas  x 6/12i if no improvement then get expert opinion plese 
183	Adapalene 0.1% aqueous gel Topical Acne	Adapalene 0.1% aqueous gel Topical 	Adapalene 0.1% aqueous gel. Apply thin film once daily at bedtime x 1/12 and repeat x 6/12 if no imprvement then get expert opinion please 
113	Adapalene 0.1% w/w cream or gel (Differin®)	Adapalene 0.1% w/w cream or gel (Differin)	"Adapalene 0.1% w/w cream or gel (Differin)\n\nApply twice weekly to affected area to start and slowly increase frequency as tolerated. Review after 3 months. if no improvement then get dermatology opinion please "
131	Almogran (Almotriptan) Migraine	Almogran (Almotriptan) 	"12.5mg. P.O. O.D/P.R.N. Dispense pack \n\nIf another attack occurs after the initial dose, a second dose maybe taken after 2 hour interval.\n\nIf there is no response to the initial dose DO NOT administer another dose."
12	Almotriptan 12.5mg (Almogran)	Almotriptan 12.5mg 	" 12.5mg \n\nOne to be taken at the onset of symptoms and repeat after 2 hours if second dose did not help then do not take 3rd dose "
312	Alopecia Finasteride Hair loss	Alopecia Finasteride 	"Finasteride 1 mg P.O. O.D,  \n"
167	Alphaderm cream topical Steroid	Alphaderm cream topical Steroid	B.D x 7/7 Dispense 30g. Apply sparling to the affected area.
196	Aluminium chloride hexahydrate 20%	Aluminium chloride hexahydrate 20%	"Aluminium chloride hexahydrate 20%   dispense 1 x 75mls\n\nApply at night to dry skin, wash off the following morning, initially apply daily then reduce frequency as condition improves do not shower immediately before use."
42	Amitiza (Lubiprostone) for constipation	Amitiza (Lubiprostone) for constipation	Amitiza (Lubiprostone) 24 Microgram Soft Capsules one capsule to be taken taken twice daily. x 1/12
192	Amitriplyline	Amitriplyline	"Amitriplyline Specify dose 10/20/30 mgs P.O nocte x 1/12. Repeat x 6/12.\n"
318	Amoxicillin Abx	Amoxicillin Abx	Amoxicillin 500mg to be taken orally three times a day for five days
246	Amoxicillin Syrup 125mg/5ml Paediatrics Abx	Amoxicillin Syrup 125mg/5ml Paediatrics Abx	Amoxicillin Syrup 125mg/5ml Specify dose T.I.D. x 5/7
245	Amoxicillin Syrup 250mg/5ml Paediatrics Abx	Amoxicillin Syrup 250mg/5ml Paediatrics Abx	Amoxicillin Syrup 250mg/5ml T.I.D. x 5/7
108	Antimalarial (Malarone- Atovaquone/Proguanil hydrochlorid)	Antimalarial (Malarone- Atovaquone/Proguanil hydrochlorid)	"250 mg/100 mg film-coated tablets Atovaquone/Proguanil hydrochloride  x14 day trip \nDosage: \nOne tablet to be taken once a day, commencing two days prior to entering malaria area continuing during and for one week after leaving area "
185	Arcoxia NSAID Analgesia	Arcoxia NSAID 	" Specify dose 30mg and 60mgs 1 tab with food daily x  1/12. \n\n"
186	Artelac single use eye drops	Artelac single use eye drops	Artelac single use drops. Insert 3-5 times daily as required. Keep in the fridge. Dispense 1 box and repeat x 1.
266	Atorvastatin	Atorvastatin	SPECIFY STRENGTH 20/ 40/ 80mg. P.O. O.D. x 1/12 repeat 6/12.
268	Atovaquone (Malarone) Malaria Prophylaxis	Atovaquone (Malarone) Malaria Prophylaxis	Atovaquone (Malarone) 250mg tablets.1 tab P.O.O.D.  X (SPECIFY NO OF DAYS OF TREATMENT)  tablets.
293	Atrovent  Inhlaer	Atrovent  Inhlaer	" 20mcg  1-2 puffs P.R.N O.P.x 1 and repeat x 2 \n\nTHIS INHALER SHOULD NOT BE USED FOR REGULAR MAINTENANCE THERAPY. MORE THAN ONCE WEEKLY USEAGE INDICATES POOR ASTHMA CONTROL."
277	Avamys Fluticasone Fuorate Nasal Spray	Avamys Fluticasone Fuorate Nasal Spray 27.5mcg	"2 sprays in each nostril once daily until symptoms are controlled and then reduce to one spray to each nostril mane as maintenance for another week \n"
101	Azalia	Azalia	" 75 microgram film-coated tablets \n\nTablets must be taken every day at about the same time so that the interval between two tablets always is 24 hours. The first tablet should be taken on the first day of menstrual bleeding. Thereafter one tablet each day is to be taken continuously, without taking any notice on possible bleeding. A new blister is started directly the day after the previous one. 1/12 and repeat 6/12"
61	Azelaic acid 15% gel  (Skinoren®) Acne	Azelaic acid 15% gel  (Skinoren)	"   Apply every 12 hours one  after 3 months if no imprvement get dermatologist opinion please \n"
62	Azithromycin 250mg [ 8 Tablets ] Chlamydia	Azithromycin 250mg [ 8 Tablets ]	 Take FOUR tablets at the same time as a single dose on day one of treatment and then TWO tablets once a day for days two and three of treatment. Dispense 8 tablets
231	Azithromycin Abx chlamydia 2nd line treatment	Azithromycin 	" 1g P.O stat. , followed by 500mg once daily for two days.\n\n"
73	Azithromycin for Traveller's diarrhea	Azithromycin 	 1000mg STAT or 500mg PO OD for 3 days.
86	Back or muscular pain	Vimovo 	"1. Vimovo Tabs. One P.O. B.D.  x 2/52\n2. (Difene) Diclofenac Sodium Spray Gel 4% TDS. Mitte 25g spray"
49	Baclofen 10/20mg spasm muscle relaxant	Baclofen 	 10mg Or 20mg three times a day for 5 days
55	Bactroban 2% w/w Nasal Ointment	Bactroban 2% 	"\n\nA small amount of the ointment about the size of a match head is placed on the little finger and applied to the inside of each nostril. The nostrils are closed by pressing the sides of the nose together; this will spread the ointment throughout the nares. A cotton bud may be used instead of the little finger for the application in particular to infants or patients who are very ill.\n5/7"
302	Beclazone Easi Breathe + Salbutamol Inhaler	Beclazone Easi Breathe + Salbutamol Inhaler	"1. 100mcg 2 puffs twice daily x 1/12 can be use for 3 months and repeat the same dose if required \n\n\n\n2.) Salbutamol  2puffs as require for short term "
77	Beclazone Easibreath 200mcg and  Salbutamol	Beclazone Easibreath 200mcg and  Salbutamol	"1.  Beclazone Easibreath 200mcg  1 puff B.D. 1/12 and repeat 6/12.\n\nALWAYS GARGLE WITH WATER AFTER USING THIS INHALER.\n\n2.  Salbutamol/Ventolin Inhaler. 100mcg 1 puffs P.R.N O.P.x 1 and repeat x 2 \n\nTHIS INHALER SHOULD NOT BE USED FOR REGULAR MAINTENANCE THERAPY. MORE THAN ONCE WEEKLY USEAGE INDICATES POOR ASTHMA CONTROL."
58	Beconase Aqueous Nasal Spray (Beclometasone Dipropionate	Beconase Aqueous Nasal Spray (Beclometasone Dipropionate	"Beconase Aqueous Nasal Spray (Beclometasone Dipropionate 50μg (as monohydrate, micronised) 2 sprays to each nostril mane x 2/52 and then when symptoms are controlled, reduce to 1 spray each nostril mane as maintenance. x 1/12 and repeat x 6/12.\n\nALWAYS GARGLE WITH WATER AFTER USING THIS NASAL SPRAY. "
130	Beconase nsasal spray	Beconase nsasal spray	Beconase nsasal spray 100mcg. 2 sprays in each nostril  twice daily x 14 days. Once symptoms are under control one spray on each nostril twice daily. Repeat x 1/12
194	Betacap Scalp Application Topical Steroids	Betacap Scalp Application Topical Steroids	Betacap Scalp Application B.D. for one week and then reduce to night for the second week and then reduce to alternate night for the third week and then stop.
193	Betnesol  steroids rinse	Betnesol  steroids rinse	Betnesol 500mcg tablets Q.I.D,  Dissolve 1 in 10 mls of warm water and gargle Dispense 30 tabs. Do not swallow Repeat x 5
214	Betnesol N Ear Drops Steroid	Betnesol N Ear Drops Steroid	Betnesol N Ear Drops: 2-3 drops into the affected ear(s) T.I.D x 1/52
177	Betnesol Nasal drops Steroids	Betnesol Nasal drops Steroids	"Betnesol Nasal drops. 2-3 drops in each nostril B.D x 1/52\n\n"
252	Betnovate ointment Topical Steroid	Betnovate ointment Topical Steroid	"Betnovate ointment. x 1\n"
204	Betnovate Scalp Application Topical Steroid	Betnovate Scalp Application Topical Steroid	"Betnovate Scalp Application 0.1% x 100mls. x 1 and repeat x 1\n\nApply sparingly, weekly when maintenance is required"
296	Bricanyl Turbohaler Inhaler	Bricanyl Turbohaler Inhaler	"Bricanyl Turbohaler 1 puffs P.R.N O.P.x 1 and repeat x 2 \n\nTHIS INHALER SHOULD NOT BE USED FOR REGULAR MAINTENANCE THERAPY. MORE THAN ONCE WEEKLY USEAGE INDICATES POOR ASTHMA CONTROL."
2	Bricanyl® Turbohaler®	Bricanyl Turbohaler	"500micrograms per metered dose, inhalation powder (terbutaline sulphate) 1 puffs P.R.N O.P.x 1 and repeat x 2 \n\nTHIS INHALER SHOULD NOT BE USED FOR REGULAR MAINTENANCE THERAPY. MORE THAN ONCE WEEKLY USEAGE INDICATES POOR ASTHMA CONTROL."
87	Candida balanitis (Male thrush-yeast infection)	Candida balanitis (Male thrush-yeast infection)	"Cloritomazole 1% cream\n\nApply twice daily topically for 5-7 days. Oral treatment is rarely indicated."
222	Canesten Cream Antifungal Topical	Canesten Cream Antifungal Topical	Canesten (Clotrimazole) Cream 2%.  T.I.D. x 1/52 then reduce to B.I.D. until symptoms settle and then Nocte x 2/52 and then alternate nights x 2/52 and then stop if symptoms are settled.
221	Canesten Pessary Antifungal Thrush	Canesten Pessary Antifungal Thrush	Canesten 200mg Pessary. Insert one pessary daily, Nocte, x 3/7.  Dispense 3 pessaries
224	Canesten-HC Cream Topical Antifungal	Canesten-HC Cream Topical Antifungal	Canesten-HC Cream T.I.D. x 1/52 then reduce to B.I.D. x 1/52 and then nocte x 1/52 and then alternate nights x 1/52 and then stop. Apply sparingly to the affected areas and avoid prolonged continuous use.
234	Cefalexin  Abx	Cefalexin  Abx	"Cefalexin 500mg P.O. T.I.D. x 1/52\n"
233	Cefalexin 125/5ml Paediatric Abx	Cefalexin 125/5ml Paediatric Abx	"Cefalexin 125/5ml. 5ml P.O. T.I.D.  x 1/52\n\n"
232	Cefalexin 250/5ml Paediatric Abx	Cefalexin 250/5ml Paediatric Abx	"5ml suspension. 5ml P.O. T.I.D.  x 1/52\n\n"
338	Cerazette tablets [ 168 Tablets ]	Cerazette tablets [ 168 Tablets ]	"CERAZETTE\nCerazette tablets [ 168 Tablets ]\n\nDirections to use : Take one tablet daily, at the same time every day. "
330	CHAMPIX smoking cessation	CHAMPIX smoking cessation	"CHAMPIX\nFor further instructions please read the leaflet"
213	Chloramphenicol 0.5% eye drops Abx	Chloramphenicol 0.5% eye drops 	 2 drops into the affected eye(s) Q.I.D. Continue for 48 hours after the symptoms have resolved.
212	Chloramphenicol 1% ointment eye Abx	Chloramphenicol 1% ointment eye Abx	1 application of ointment into the affected eye(s) Q.I.D. Continue for 48 hours after the symptoms have resolved.
35	Chloromycetin 0.5% Redidrops ear drops (can be used for less than 2 years)	Chloromycetin 0.5% Redidrops ear drops (can be used for less than 2 years)	Chloromycetin 0.5% Redidrops 2 drops into the affected ear(s) Q.I.D. Continue for 48 hours after the symptoms have resolved.
198	Chlorphenamine  syrup Paediatrics Antihistamine	Chlorphenamine  syrup Paediatrics Antihistamine	"Chlorphenamine maleate 2mg/5mL Syrup  2.5mls nocte (150mls)        \n\nChild 1–23 months\n\n1 mg twice daily.\n\nChild 2–5 years\n\n1 mg every 4–6 hours; maximum 6 mg per day.\n\nChild 6–11 years\n\n2 mg every 4–6 hours; maximum 12 mg per day.\n\nChild 12–17 years\n\n4 mg every 4–6 hours; maximum 24 mg per day."
334	CIALIS 2.5/5/10/20mg ED	CIALIS 2.5/5/10/20mg ED	"Cialis (Tadalafil) DOSE mg 4 tablets x 6 [ 24 (maximum) tablets]\n1 tablet P.O. 30 minutes before sexual activity to max 1 tablet in any 36 hours.\nFor further instructions please read the leaflet"
4	Cilest	"Cilest 250/35microgram Tablets (norgestimate, ethinylestradiol)\n"	"\nThe tablets must be taken every day at about the same time, if necessary with a little liquid, in the order shown on the blister pack. One tablet is to be taken daily for 21 consecutive days. Every subsequent blister pack is started after a 7-day tablet-free interval  during which time a withdrawal bleeding usually occurs.  Mitte x 1/12 & Repeat for 6/12.\nFurther instructions are in your Patient Record."
346	Cilique tablets 6 months supply [ 126 Tablets ]	Cilique tablets 6 months supply [ 126 Tablets ]	"CILIQUE\nCilique tablets 6 months supply [ 126 Tablets ]\n\nDirections to use : One tablet daily for 21 days."
138	Cimetidine Antacid	Cimetidine Antacid	Cimetidine 400 mg 1 tablet P. O B.D. Dispense * 56 tablets
243	Ciprofloxacin Abx	Ciprofloxacin 	Specify 250mg or 500mg P.O.B.D. Dispense 14 tabs.
82	Clarithromycin	Clarithromycin	Clarithromycin 500mg. P.O. B.D. x 5/7 or 7days
127	Clarithromycin 125mg/5mls Paediatric Abx	Clarithromycin 125mg/5mls Paediatric Abx	" Oral Solution 125mg/5mls B.D x 5/7\n"
126	Clarithromycin 250mg/5mls Paediatric Abx	Clarithromycin 250mg/5mls 	" Oral Solution 250mg/5mls P.O, B.D x 5/7\n\n"
72	Clindamycin 2% cream	Clindamycin 2% cream	"2% cream 5g applicatorful inserted intravaginally at night for 7 nights\n\nAvoid clindamycin cream in first trimester.\n\nClindamycin cream can weaken latex condoms/diaphragms, which should not be used during treatment and for 72 hours afterwards."
22	Clindamycin 2% cream OR 5g applicatorful inserted intravaginally  for bacterial vaginosis	Clindamycin 2% cream OR 5g applicatorful inserted intravaginally  for bacterial vaginosis	"2% cream OR 5g applicatorful inserted intravaginally at night 7 nights Avoid clindamycin cream in first trimester. Clindamycin cream can weaken latex condoms/diaphragms, which should not be used during treatment and for 72 hours afterwards.\n"
23	Clindamycin capsules 300mg for bacterial vaginosis	Clindamycin capsules	" 300mg orally every 12 hours 7 days\n"
238	Clindamycin Cream Abx PV	Clindamycin Cream 	" One applicator full P.V. nocte x 1/52.\n\n"
258	Clobetasol (Dermovate) ointment Topical Steroid	Clobetasol (Dermovate) ointment Topical	" 0.05% ointment x 30g \n\nApply sparingly to the affected area B.D. x1/52 and then reduce to  nocte x1/52 and then alternate nocte x/152 and then stop.\n\nAvoid prolonged daily use of this ointment."
92	Cloritomazole 1% cream OTC (Vulvovaginal candidiasis or Vaginal thrush)	Cloritomazole 1% cream OTC 	"\n\nApply to the affected area 2-3 times a day, until the symptoms resolved. Up to 7 days. Should be continued for external relief of symptoms in addition to intravaginal or systemic antifungal if required. "
93	Cloritomazole 2% cream OTC (Vulvovaginal candidiasis or Vaginal thrush)	Cloritomazole 2% cream OTC 	"\n\nApply to the affected area 2-3 times a day, until the symptoms resolved. Up to 7 days. Should be continued for external relief of symptoms in addition to intravaginal or systemic antifungal if required. "
94	Cloritomazole 500mg pessary OTC (Vulvovaginal candidiasis or Vaginal thrush)	Cloritomazole 	" (Canestan) 500mg pessary Single dose\n\nInsert the pessary using applicator. Use of an applicator is not recommended during pregnancy. Latex condoms and diaphragms ca be damaged by vaginal creams and pessaries, extra precautions are advised."
121	Co-amoxiclav  Abx	Co-amoxiclav  	 500/125mg. P.O. T.I.D x 5/7 or 7days
125	Co-amoxiclav 125/31.25 mg Paediatrics Abx	Co-amoxiclav 125/31.25 mg Paediatrics 	 125/31.25mg in 5mL Oral Suspension SPECIFY DOSET.I.D. x 5/7
203	Codinex Syrup cough	Codinex Syrup	" 5-7.5 mls P.O Q.I.D /P.R.N X 5 days. Dispense 100/150mls\n\n"
34	Colchicine  for acute gout attack	Colchicine  	 500 microgram 1 tablet to be taken orally 3 times a day for 5 days
143	Colchicine Gout	Colchicine 	"Colchicine 500 microgram Tablet. Dispense 12 tablets.\n\nUse as directed by your doctor."
161	Colecalciferol Vitamin D	Colecalciferol Vitamin D	"Colecalciferol 20,000 IU One capsule orally, twice per week x 7/52.\n"
169	Colofac Mebeverine hydrochloride IBS	Colofac Mebeverine hydrochloride	tabs. P.O T.I.D, 1 tab to be taken 20 minutes before eating food. Dispense 90 tabs.
158	Corsodyl 0.2 % w/v Aniseed Mouthwash.	Corsodyl 0.2 % w/v Aniseed Mouthwash.	" 10mls B.D Dispense 300mls bottle.\n\nRinse mouth for 1 minute and spit out after use. Avoid prolonged use."
50	Cough syrup Bisolvon 4mg/5ml Oral Solution (Children 2 to ≤ 5 years)	Cough syrup Bisolvon 4mg/5ml Oral Solution (Children 2 to ≤ 5 years)	"Bisolvon 4mg/5ml Oral Solution\n\n5 ml (4 mg) twice daily."
51	Cough syrup Bisolvon 4mg/5ml Oral Solution (Children over 5 to ≤ 12 years)	Cough syrup Bisolvon 4mg/5ml Oral Solution (Children over 5 to ≤ 12 years)	"Bisolvon 4mg/5ml Oral Solution \n\n5 ml (4 mg) four times daily"
52	Cough syrup Bisolvon 4mg/5ml Oral Solution for adults	Cough syrup Bisolvon 4mg/5ml Oral Solution for adults	"Bisolvon 4mg/5ml Oral Solution\n\n10 ml (8 mg) three times daily, maximum dose 15 ml (12 mg) four times daily"
247	Crestor Rosuvastatin	Crestor Rosuvastatin	Specify 5/10/20 mg P.O.O.D. x 1/12 repeat 6/12
146	Crotamiton 10% w/w (Eurax) cream Topical Itch	Crotamiton 10% w/w (Eurax) cream Topical Itch	Crotamiton 10% w/w (Eurax) cream. Apply twice per day to affected areas. Dispense 100g.
43	Cyklokapron 500 mg (Tranexamic acid) for Menorrhagia	Cyklokapron 500 mg (Tranexamic acid) for Menorrhagia	Cyklokapron 500 mg 2 tablets 3 times daily for 1/52
71	Daktacort 2% / 1% w/w Cream	Daktacort 2% / 1% w/w Cream	"Daktacort 2% / 1% w/w Cream (Miconazole nitrate 2%w/w and hydrocortisone 1%w/w)\n\nApply one to three times daily to the affected area. Daktacort cream should be rubbed in gently until it has been completely penetrated into the skin. The treatment with Daktacort cream (or subsequently with miconazole nitrate 20 mg/g cream) should be continued without interruption until the lesion has completely disappeared (usually after 2 to 6 weeks)\n"
225	Daktacort Cream Topical Antifungal	Daktacort Cream topical	" T.I.D. x 3/7 then reduce to B.I.D. x 1/52 and then nocte x 1/52. \n\nApply sparingly to the affected areas Avoid prolonged continuous use of this ointment."
220	Daktarin Cream Topical Antifungal	Daktarin Cream Topical 	 T.I.D. x 1/52 then reduce to B.I.D. until symptoms settle and then Nocte x 2/52 and then alternate nights x 2/52 and then stop if symptoms are settled.
201	Dalacin T Solution/lotion clindamycin Abx Acne	Dalacin T Solution/lotion clindamycin Abx Acne	Dalacin T Solution/lotion B.D. to the affected area. x 1/12 and repeat x  6/12.
271	DAPOXETINE  Premature ejaculation	DAPOXETINE  	" 30 mg  Dispense 1 box x 6 tablets. Repeat x 5 times.\n\n1 tablet 1-3 hours prior to sexual activity to maximum of 1 tablet in 24 hours. Take with plenty of water. Avoid drinking alcohol when using this medicine."
114	Depression and insomnia- Mirtazapine	Depression and insomnia- 	Mirtazapine 15mg to be taken once a day in the night 1/12 and repeat for 3/12
139	Deslor Paediatric Antihistamine	Deslor Paediatric 	" 0.5 mg/ml Oral Solution (Desloratidine) Dispense 100mls\n\nDosage:\n\n1-5yrs 2.5 ml (1.25 mg) Deslor oral solution once a day\n6-11yrs 5 ml (2.5 mg) Deslor oral solution once a day\n12yrs and above  10 ml (5 mg) oral solution once a day"
265	Desloratidine Antihistamine	Desloratidine 	" 5mg P.O. O.D. x 1/12 repeat 6/1\n"
342	Dianette tablets [ 126 Tablets ] for Acne	Dianette tablets 	"\n\nDirections to use : One tablet daily for 21 days."
209	Diclofenac + PPI NSAID Analgesia	Diclofenac + PPI NSAID Analgesia	"Diclofenac 50mg P.O. T.I.D. x 1/52 and repeat x 3 times.\n\nEsomeprazole 20mg P.O O.D x 1/52 and repeat x 3 times."
273	Diclofenac retard NSAID Analgesia	Diclofenac retard NSAID Analgesia	Diclofenac retard. 75mg P.O. B.D x 1/52 repeat x 4
137	Diclofenac Sodium Spray Topical NSAID Analgesia	Diclofenac Sodium Spray Topical NSAID Analgesia	Diclofenac Sodium Spray Gel 4%  T.I.D/P.R.N. Dispense 25g spray. Repeat x 3
325	Diflucan (Fluconazole) antifungal Thrush	Diflucan (Fluconazole) 	"150mg caps. One P.O. at onset of symptoms. If not settled after 72 hours, repeat x once. Mitte O.P.x 1 and repeat x once P.R.N.\n\nFor further instructions please read the leaflet"
152	Diphenhydramine Hydrochloride Antihistamine	Diphenhydramine Hydrochloride 	" 50mg tablets. 1/2 or 1 full tablet, one to two hours before bed. 16 tablets.\n\nNot recommended in the 2 weeks prior to delivery or for use in breastfeeding. Can cause dizziness and drowsiness - do not operate machinery or drive if affected"
292	Distaclor L.A Abx	Distaclor L.A Abx	 375mb P.O. B.D. x 1/52. 
44	Distaclor LA 375 mg for recurrent tonsilitis	Distaclor LA 375 	one tablet to be taken twice daily for 7 days.
153	Doublebase emollient topical	Doublebase emollient gel	"2-3 times daily,  Dispense 500g. Repeat x 6\n\n"
83	Dovobet - psoriasis	Dovobet - psoriasis	"Dovobet® 50micrograms/g+0.5mg/g Gel (calcipotriol / betamethasone) - Use the gel once a day (Maximum 15gper day) for 4 weeks for scalp areas and 8 weeks for non-scalp areas. \n\nApply Dovobet to the affected area with your fingertips, and rub it in gently until the area affected by psoriasis is covered by a thin layer of gel. Cutaneous use only."
195	DOVOBET Gel Topical Steroid	DOVOBET Gel Topical Steroid	 30g betamethasone (as dipropionate) 0.05%,calcipotriol (as monohydrate) 50 micrograms/g x 4/52
180	Doxycycline 100mg Abx Acne	Doxycycline 100mg 	"100mg P.O O.D x 3/12\n\nUse SPF and avoid strong sun exposure. Avoid pregnancy while using this medication. Take with a glass of water or food"
230	Doxycycline Abx Chlamydia 1st line	Doxycycline Abx Chlamydia 1st line	" Doxycycline 100 mg B.D x7/7\n\nAvoid in pregnancy and breastfeeding."
21	Doxycycline and Ivermectin Rosacea	Doxycycline and Ivermectin Rosacea	"Ivermectin 10mg/g cream (Soolantra®) Apply thinly every 24 hours to the affected area at night 1/12 and repeat 3/12\n\nDoxycyline modified release 40mg one tablet to be taken every 24 hours  orally 1/12 and repeat 3 months\n\nReview 3 months"
103	Doxycycline for Sinusitis/RTI	Doxycycline for Sinusitis/RTI	"Doxycycline 200mg every 24 hours orally for 5 days\n\nAvoid in pregnancy. Advise to take with a glass of water and sit upright for 30 minutes after taking. Can take with food or milk if gastritis is an issue."
250	Drynol Bilastine Antihistamine	Drynol Bilastine Antihistamine	Drynol (Bilastine) 20mg P.O. O.D. x 1/12 repeat 6/12
200	Duac Cream Abx Topical	Duac Cream Abx Topical	"Duac Cream: Apply O.D. to the affected area. Repeat x 3/12.\n"
184	Duloxetine  antidepressant	Duloxetine  antidepressant	"Duloxetine 60mg P.O O.D x 1/12\n\n"
295	Duoresp Spiromax  Inhaler	Duoresp Spiromax  Inhaler	"Duoresp Spiromax 160 mcg/4.5 mcg. 2 puffs B.D.  x 1/12 and repeat x 6/12\n\nALWAYS GARGLE WITH WATER AFTER USING THIS INHALER."
253	Dymista Nasal Spray Sinusitis	Dymista Nasal Spray Sinusitis	"Dymista Nasal Spray: One spray to each Nostril twice daily until symptoms are controlled and then reduce to one spray to each nostril once daily x 1/12. repeat 6/12.\n\nGargle with water after using spray."
20	E45 Cream	E45 Cream	E45 Cream White Soft Paraffin 14.5% w/w Light Liquid Paraffin 12.6% w/w Anhydrous Lanolin 1.0% w/w Apply topically to the affected part two or three times daily 
91	Econazole (Gyno-Pevaryl) pessary OTC for genital thrush	Econazole (Gyno-Pevaryl) pessary OTC for genital thrush	"Econazole (Gyno-Pevaryl) pessary 150mg PV single dose \n\nInsert pessary using applicator. Use of an applicator is not recommended during pregnancy. Latex condoms and diaphragms ca be damaged by vaginal creams and pessaries, extra precautions are advised."
67	ellaOne 30mg	ellaOne 30mg	"ellaOne 30mg Please dispense ONE tablet only.\n\nThe tablet should be taken as soon as possible after sexual intercourse. \n"
219	Elocon Ointment Topical Steroid	Elocon Ointment Topical Steroid	Elocon Ointment nocte x 10/7 then reduce to alternate nocte x 10/7 and then stop. Apply sparingly to the affected areas and avoid prolonged continuous use.
174	Eltroxin Levothyroxine	Eltroxin Levothyroxine	"Eltroxin/Levothyroxine Specify dose.  P.O O.D. x 6/12 \n\nTake in the morning, on an empty stomach and do not eat for 30 minutes."
111	Elvina combined contraceptive pill	Elvina combined contraceptive pill	"Elvina 0.03mg/3mg (0.03 mg ethinylestradiol and 3 mg drospirenone.)\n\nThe tablets must be taken every day at about the same time, if necessary, with a little liquid, in the order shown on the blister pack. One tablet is to be taken daily for 21 consecutive days. Each subsequent pack is started after a 7-day tablet-free interval, during which time a withdrawal bleed usually occurs. This usually starts on day 2-3 after the last tablet and may not have finished before the next pack is started. Miite 1/12 and repeat 6/12"
256	Emla nNumbing Cream Topical	Emla nNumbing Cream Topical	"Emla Cream 5% \n\nLeave in contact for 15 minutes then wash off prior to activity. 1 tube and repeat x 6."
175	Epiduo Gel Topical Acne	Epiduo Gel Topical Acne	Epiduo Gel.  Apply once daily on clean dry acne skin, in the evening. Do not apply to irritated/damaged skin repeat x 6
69	Epilim (Valproate)	Epilim (Valproate)	Epilim Chrono 500mg PO OD x 1/12 and repeat 6/12
240	Erythromycin  Abx	Erythromycin  Abx	"Erythromycin 500mg tabs. P.O. B.D. x 1/52.\n\n"
239	Erythromycin Paediatric Syrup Abx	Erythromycin Paediatric Syrup Abx	" Erythromycin Syrup125mg/5ml. P.O. B.D x 1/52\n\nSpecify dose on weight basis at 30mg/kg weight of child."
311	Escitalopram Antidepressant	Escitalopram Antidepressant	"Escitalopram 5 / 10/ 20 mg tabs One P.O. O.D. x 1/12 and repeat x 3/12.\n"
291	Esomeprazole PPI	Esomeprazole PPI	"Esomeprazole 20 / 40 mg  P.O. O.D.  x 1/12 and repeat x 6/12.\n"
164	Estrogel Pump Utrogestan tablets HRT	Estrogel Pump Utrogestan tablets HRT	"Estrogel Pump [0.06% w/w]  1-2 pump daily x 1/12. Repeat x 6/12\n\nUtrogestan tablets 100mgs 1 daily PO x 1/12 Repeat x 6/12"
150	Etoflam 5% Cream Topical NSAID Analgesia	Etoflam 5% Cream Topical NSAID Analgesia	"Etoflam 5% Cream. T.I.D/P.R.N x 1 tube. Massage well into affected area. \n\n"
27	Eumovate Cream 0.05% w/w	Eumovate Cream 0.05% w/w	"Eumovate Cream 0.05% w/w Apply thinly and gently rub in using only enough to cover the entire affected area once or twice a day until improvement occurs, then reduce the frequency of application\n\nMitte x 4 weeks"
275	Eumovate Ointement Topical Steroid	Eumovate Ointement Topical Steroid	Eumovate Ointement. Apply sparingly to the affected areas T.I.D. x 1/52 then reduce to B.I.D. x 1/52, and then Nocte x 1/52 and then alternate nights x 1/52 and then stop. Avoid prolonged continuous use of this ointment.
347	Evra (patches) [ 18 Patches ]	Evra (patches) [ 18 Patches ]	"EVRA (PATCHES)\nEvra (patches) [ 18 Patches ]\n\nDirections to use : Apply first patch on day 1 of cycle, change patch on days 8 and 15; remove third patch on day 22 and apply new patch after 7-day patch-free interval to start subsequent contraceptive cycle"
211	Exocin Ofloxacin Opthalmic Drops Abx	Exocin Ofloxacin Opthalmic Drops Abx	Exocin (Ofloxacin) Opthalmic Drops. 1-2 drops into the affected eye(s) up to Q.I.D. . Continue for 48 hours after the symptoms have resolved, maximum of 10 days treatment.
15	EXOCIN: ofloxacin 0.3% w/v eye drops	EXOCIN: ofloxacin 0.3% w/v eye drops	"EXOCIN: ofloxacin 0.3% w/v eye drops,\n\n2 drops into the affected eye(s) Q.I.D. Continue for 48 hours after the symptoms have resolved."
236	Famciclovir Antiviral	Famciclovir Antiviral	"Famciclovir 500mg One P.O. T.I.D.  Dispense x 21 tabs. \n\n"
142	Femoston-conti  HRT	Femoston-conti  HRT	Femoston-conti 1mg/ 5mg film-coated tablets. P.O O.D, Dispense 28 tablets. Repeat x 6
199	Fesoterodine Antihistamine	Fesoterodine Antihistamine	"Fesoterodine (Toviaz) 4mg  P.O. O.D. x 1/12 and repeat x 1/12.\n\n"
65	Finasteride 1 mg	Finasteride 1 mg	Finasteride 1 mg P.O. O.D, Dispense 184 tabs
66	Finasteride 5mg tablets	Finasteride 5mg tablets	"1. Finasteride 5mg tablets.  1/4 (one quarter) of one tablet (1.25mg) to be taken daily.   Dispense x 46 tablets to provide 184 days supply. PLEASE ISSUE ALL 46 TABLETS TOGETHER. \n\n2. Please offer to supply a pill cutter. "
119	Flagyl (Metronidazole) 400mg tabs.- Bacterial vaginosis	Flagyl (Metronidazole) 400mg tabs.- Bacterial vaginosis	"Flagyl (Metronidazole) 400mg tabs. One P.O. B.D. for 1 week.\n\nAvoid taking alcohol when using this medicine and for 72 hours after. Mitte x 14 tabs."
303	Flixotide  + Ventolin inhaler	Flixotide  + Ventolin inhaler	"1. Flixotide 50 mcg Discus inhaler: 1 puffs B.D. x 1/12 and repeat x 6/12\n\nALWAYS GARGLE WITH WATER AFTER USING THIS INHALER.\n\n\n2. Salbutamol/Ventolin Inhaler. 100mcg 1 puffs P.R.N O.P.x 1 and repeat x 2 \n\nTHIS INHALER SHOULD NOT BE USED FOR REGULAR MAINTENANCE THERAPY. MORE THAN ONCE WEEKLY USEAGE INDICATES POOR ASTHMA CONTROL."
78	Flixotide Evohaler 125mcg and Ventollin	Flixotide Evohaler 125mcg and Ventollin	"1.  Flixotide Evohaler 125mcg 1 puff B.D. 1/12 and repeat 6/12.\n\nALWAYS GARGLE WITH WATER AFTER USING THIS INHALER.\n\n2.  Salbutamol/Ventolin Inhaler. 100mcg 1 puffs P.R.N O.P.x 1 and repeat x 2 \n\nTHIS INHALER SHOULD NOT BE USED FOR REGULAR MAINTENANCE THERAPY. MORE THAN ONCE WEEKLY USEAGE INDICATES POOR ASTHMA CONTROL."
124	Flucloxacillin 125mg/5ml Paediatrics Abx	Flucloxacillin 125mg/5ml Paediatrics Abx	Flucloxacillin powder for oral suspension 125mg/5ml SPECIFY DOSE Q.I.D x 7/7
123	Flucloxacillin 250mg/5ml Paediatrics Abx	Flucloxacillin 250mg/5ml Paediatrics Abx	Flucloxacillin powder for oral suspension 250mg/5ml SPECIFY DOSE Q.I.D x 7/7
323	Flucloxacllin Abx	Flucloxacllin Abx	Flucloxacillin 500mg P.O Q.I.D x 7/7
317	Fluoxetine 20mg antidepressant	Fluoxetine 20mg antidepressant	"Fluoxetine 20mg capsules. One capsule daily. Mitte x 1/12 and repeat 3/12\n\nSeek a review with your GP if you feel your mental health is getting worse"
210	Fosfomycin Abx UTI	Fosfomycin Abx UTI	Fosfomycin 3g O.D stat. x 1/7
99	Freedo	Freedo	"Freedo (0.03 mg of ethinylestradiol and 3 mg of drospirenone) film-coated tablets\n\nThe tablets must be taken every day at about the same time, if necessary with a little liquid, in the order shown on the blister pack. One tablet is to be taken daily for 21 consecutive days. Every subsequent blister pack is started after a 7-day tablet-free interval  during which time a withdrawal bleeding usually occurs.  Mitte x 1/12 & Repeat for 6/12."
104	Freedonel	Freedonel	"Freedonel (0.02 mg ethinylestradiol / 3 mg drospirenone) film-coated tablets \n\nThe tablets must be taken every day at about the same time, if necessary with a little liquid, in the order shown on the blister pack. One tablet is to be taken daily for 21 consecutive days. Every subsequent blister pack is started after a 7-day tablet-free interval  during which time a withdrawal bleeding usually occurs.  Mitte x 1/12 & Repeat for 6/12.\n"
133	Frovex (Frovatriptan)  Migraine	Frovex (Frovatriptan)  Migraine	"Frovex (Frovatriptan) 2.5mg. P.O. O.D/P.R.N. Dispense pack of 6 and repeat x 6/12\n\nDo not exceed more than 5mg in any 24 hour period. If another attack occurs after the initial dose another tablet maybe taken after 2 hour interval. If there is no response to the initial dose DO NOT administer another dose"
202	Fucibet lipid Topical Fusidic acid 2% and Betamethasone 0.1%	Fucibet lipid Topical Fusidic acid 2% and Betamethasone 0.1%	Fucibet lipid apply sparingly to affected area 1x1/52.
284	Fucidin 20mg/g Topical	Fucidin 20mg/g Topical	Fucidin 20mg/g Cream/Ointment Q.I.D to affected area Dispense *15g
285	Fucidin H cream Topical	Fucidin H cream Topical	Fucidin H cream. Apply to the affected area every 8 hours for five days, then reduce to twice a day for the next five days and then reduce to nocte for the final five days and then stop. To be applied sparingly. Mitte x 15g.
286	Fucidin Ointment Topical	Fucidin Ointment Topical	Fucidin Ointment Apply Q.I.D. to the affected area. O.P. x 1. Wash your hands after using this ointment.
36	Fucithalmic 10mg/g Viscous Eye Drops - Fuscidic acid	Fucithalmic 10mg/g Viscous Eye Drops - Fuscidic acid	Fucithalmic 10mg/g Viscous Eye Drops, suspension One drop of Fucithalmic viscous eye drop, should be applied to the conjunctival sac every 12 hours. Treatment should be continued for 2 days after the eye appears normal.
74	Fusidic acid 1% viscous eye drops suspension	Fusidic acid 1% viscous eye drops suspension	"Fusidic acid 1% viscous eye drops suspension \n\nApply one drop to the infected eye(s) every 12 hours. Treatment should be continued for 48 hours after resolution of symptoms"
310	Fusidic Acid eye drops Abx	Fusidic Acid eye drops Abx	Fusidic Acid opthalmic drops. instil one drop, B.D. Continue for 48 hours after the symptoms resolved.
215	Gentisone HC Ear Drops Abx Steroid	Gentisone HC Ear Drops Abx Steroid	Gentisone HC Ear Drops 2-3 drops into the affected ear(s) T.I.D x 1/52
168	Gyno Daktarin PV Antifungal	Gyno Daktarin PV Antifungal	Gyno Daktarin 20g  P.V Nocte, x 7/7
237	Gyno-Pevaryl Once Pessary  Econazole nitrate PV antifungal	Gyno-Pevaryl Once Pessary  Econazole nitrate PV antifungal	"Gyno-Pevaryl Once Pessary O.P. x 1, repeat x1 P.R.N.\n\nInsert P.V. Nocte as directed. Repeat after 5 days if not symptoms are not resolved."
313	Hair Loss - Finasteride 5mg	Hair Loss - Finasteride 5mg	"Finasteride 5mg tablets.  1/4 (one quarter) of one tablet (1.25mg) to be taken daily. \n\nDispense x 46 tablets to provide 184 days supply. \n\nPLEASE ISSUE ALL 46 TABLETS TOGETHER. \n\n                                                             \nPlease offer to supply a pill cutter. "
37	HRT - Estradot 50 Patches / Utrogestan Capsules	HRT - Estradot 50 Patches / Utrogestan Capsules	"Estradot  50 micrograms Transdermal Patch One to be applied every 3 days Mitte x 1/12. & Repeat x 6/12.\nUtrogestan oral capsule 100 mg daily at night x 1/12 and repeat 6/12"
100	HRT - Evorel Conti 50/170 micrograms Transdermal Patch	HRT - Evorel Conti 50/170 micrograms Transdermal Patch	Evorel Conti 50/170 micrograms Transdermal Patch One to be applied every 3 days Mitte x 1/12. & Repeat x 6/12.
157	Humulin M3 (Mixture 3)	Humulin M3 (Mixture 3)	Humulin M3 (Mixture 3) 100 IU/ml Suspension for Injection in cartridge. Take as directed by your doctor. Dispense 5 x 3ml cartridges. Repeat x 6
28	Hydrocortisone 1 % w/w Cream	Hydrocortisone 1 % w/w Cream	"Hydrocortisone 1 % w/w Cream to be applied topically\n\nRecommended dosage schedules:\n\nAdults: Use sparingly over a small area once or twice daily for a maximum period of one week.\n\nChildren: Hydrocortisone 1 % w/w Cream is not recommended for use in children under 12 years without medical supervision"
287	Hydrocortisone 1% Cream. Topical Steroid	Hydrocortisone 1% Cream. Topical Steroid	"Hydrocortisone 1% Cream. Apply sparingly to the affected areas B.I.D. x 1/52 maximum.  Dispense 15g.\n\nUse on the face only if specifically advised to by your doctor. Wash hands after use."
288	Hydrocortisone Steroid	Hydrocortisone Steroid	Hydrocortisone Buccal 2.5mg, Apply one tab to the affected area Q.I.D. Dispense x 20 tabs.
207	Imigran Migraine	Imigran Migraine	Imigran FTAB 50/100mg Tabs. . One to be taken at the onset of symptoms and repeat after 2 hours if symptoms are not settling. Dispense x 6 tabs. Repeat x 6/12.
165	Imigran Migraine nasal spray	Imigran Migraine nasal spray	"Imigran 10mg nasal spray Dispense 1 box and repeat x 6\n\n1-2 sprays into one nostril at the start of a migraine attack. Repeat dose at an interval of 2 hours and only if there has been some improvement of pain."
254	Imodium Loperamide anti diarrheal	Imodium Loperamide anti diarrheal	Imodium (Loperamide) 2mg 2 capsules P.O. Stat and then one T.I.D./P.R.N Dispense 20 caps.
149	Incruse ellipta Inhaler	Incruse ellipta Inhaler	"Incruse ellipta 55mcgs 1 Puff O.D x 1/12 repeat x 6/12\n\n"
97	Itraconzole, ring worm treatment	Itraconzole, ring worm treatment	"Itraconazole 400mg PO OD 2/52\n"
156	Janumet Diabetes	Janumet Diabetes	Janumet 50/1000 milligram(s) Film-coated tablet.P.O B.D . Dispense 56 tablets. Repeat x 6
244	Klacid Clarithromycin Abx	Klacid Clarithromycin Abx	Klacid LA (Clarithromycin) 500mg. P.O. B.D. x 5/7
129	Kliogest HRT	Kliogest HRT	Kliogest 2mg/1mg film-coated tablets. One tablet daily. Dispense x 28 tablets. Repeat x 3
229	Lansoprazole PPI	Lansoprazole PPI	Lansoprazole Specify 15 or 30mg P.O. O.D. x 1/12 repeat x 6/12
134	Lantus Solostar Diabetes	Lantus Solostar Diabetes	"Lantus Solostar 100units/ml 3ml Disposable Pen. Dose as per plan\nDispense x 2 Packs of 5 Pens. Repeat x 6"
98	Leonore tablets	Leonore tablets	"Leonore (0.1 mg of levonorgestrel and 0.02 mg of ethinylestradiol) coated tablets\n\nThe tablets must be taken every day at about the same time, if necessary with a little liquid, in the order shown on the blister pack. One tablet is to be taken daily for 21 consecutive days. Every subsequent blister pack is started after a 7-day tablet-free interval  during which time a withdrawal bleeding usually occurs.  Mitte x 1/12 & Repeat for 6/12."
333	LEVITRA 5/10/20mg	LEVITRA 5/10/20mg	"LEVITRA 5/10/20mg\nVardenafil {Levitra} 5/10/20mg tablets. P.O. 4 tablets x 6 [ 24 (maximum) tablets]\n\nTake 30-60mins prior to sexual activity to max 1 tablet in any 24 hours.\n\nFor further instructions please read the leaflet"
11	Levofloxacin if other 2 are not suitable	Levofloxacin if other 2 are not suitable	Levofloxacin 500 mg orally once daily for seven days
64	Levonorgestrel 1.5mg	Levonorgestrel 1.5mg	"Levonorgestrel 1.5mg Please dispense ONE tablet only.\n\nThe tablet should be taken as soon as possible after sexual intercourse. "
63	Levonorgestrel 1.5mg (Double dose)	Levonorgestrel 1.5mg (Double dose)	"Levonorgestrel 1.5mg Please dispense TWO tablet only.\n\nThe tablet should be taken as soon as possible after sexual intercourse. "
191	Loceryl Lacquer Soln. Topical Antifungal Dermatophyte Fingernails and Toenails	Loceryl Lacquer Soln. Topical Antifungal Dermatophyte Fingernails and Toenails	"Loceryl Lacquer Soln.  x 1 and repeat for 6/12.\n\nApply twice weekly to the affected nails. Apply on the same days."
217	Locoid Lipocream Topical Steroid	Locoid Lipocream Topical Steroid	Locoid Lipocream T.I.D. x 1/52 then reduce to B.I.D. x 1/52 and then Nocte x 1/52 and then alternate nights x 1/52 and then stop. Apply sparingly to the affected areas and avoid prolonged continuous use.
319	Logynon Tablets	Logynon Tablets	"Logynon Tablets (Each light brown tablet contains: Ethinylestradiol 30 micrograms Levonorgestrel 50 micrograms Each white tablet contains: Ethinylestradiol 40 micrograms Levonorgestrel 75 micrograms Each ochre-coloured tablet contains: Ethinylestradiol 30 micrograms Levonorgestrel 125 micrograms)\n\nThe memo-pack contains 21 tablets. Tablet-taking is always started from the section marked “Start” and then continued daily\ninthe direction of the arrows. Tablets must be taken in the order directed on the package every day at about the same time with some liquid as needed. One tablet is to be taken daily for 21 consecutive days. Each subsequent pack is started after a 7‑day tablet-free interval, during which time a withdrawal bleed usually occurs. This usually starts on day 2‑3 after the last coated tablet and may not have finished before the next pack is started.\n\nMitte 1/12 and repeat 6/12\n\nFurther instructions are in your Patient Record."
223	Lotriderm Cream Topical Antifungal + Steroid	Lotriderm Cream Topical Antifungal + Steroid	Lotriderm Cream. T.I.D. x 1/52 then reduce to B.I.D. x 1/52 and then nocte x 1/52 and then alternate nights x 1/52 and then stop. Apply sparingly to the affected areas and avoid prolonged continuous use.
136	Lyclear (Permethrin) Scabies	Lyclear (Permethrin) Scabies	Lyclear (Permethrin) 5% w/w Dermal Cream. Apply once. 30gm tube. Dispense 1 or 2 tubes
341	Marviol tablets [ 126 Tablets ]	Marviol tablets [ 126 Tablets ]	"MARVIOL\nMarviol tablets [ 126 Tablets ]\n\nDirections to use : One tablet daily for 21 days."
328	Medroxyprogesterone acetate {Provera}	Medroxyprogesterone acetate {Provera}	"Medroxyprogesterone acetate {Provera}\nMedroxyprogesterone acetate {Provera} 10mgs tds Mitte x 5 DAYS.\n\nDirections to use: Treatment should be started three days before menstruation is likely to begin. After discontinuing these medications, you should have a regular period in 2-3 days."
18	Mefenamic acid 250 mg for period cramps	Mefenamic acid 250 mg for period cramps	Mefenamic acid 250 mg every 6 hours 1/52
68	Melatonin 3mg	Melatonin 3mg	"Melatonin 3mg PO OD x 2/52\n\nOne tablet to be taken once a day 45 minutes before sleeping in the night for 2 weeks. The dose may be increased to 6 mg (2 tablets taken together) if the standard dose does not adequately alleviate symptoms. Review after that if needed."
339	Mercilon tablets [ 126 Tablets ]	Mercilon tablets [ 126 Tablets ]	"MERCILON\nMercilon tablets [ 126 Tablets ]\n\nDirections to use : One tablet daily for 21 days. ."
206	Metformin Diabetes	Metformin Diabetes	"Metformin 500mg P.O. B.D. x 1/12 and repeat x 6/12.\n"
41	Metoclopramide Hydrochloride 5mg/5ml	Metoclopramide Hydrochloride 5mg/5ml	Metoclopramide Hydrochloride 5mg/5ml Oral Solution  Dosage: 2.5 mg (2.5ml)  3 times daily for 5 days
122	Metronidazole 200mg/5ml Paediatrics Abx	Metronidazole 200mg/5ml Paediatrics Abx	"Metronidazole liquid 200mg/5ml SPICIFY DOSE T.I.D x 5/7\n"
241	Metronidazole Abx	Metronidazole Abx	"Metronidazole 400mg  P.O. B.D. for 1 week.\n\nAvoid drinking alcohol when using this medicine and for 72 hours after."
155	Mezavant XL  Mesalamine IBD	Mezavant XL  Mesalamine IBD	Mezavant XL 1200mg  1-2 P.O O.D X 1/12
262	Miconazole Antifungal Topical Powder	Miconazole Antifungal Topical Powder	"Miconazole Nitrate 2% Powder  x 20g, repeat x 6 times.\n\nSprinkle into both socks and shoes each morning for 1 month. Repeat for a further two months if required."
96	Miconazole vaginal cream prescription only (Vulvovaginal candidiasis or Vaginal thrush)	Miconazole vaginal cream prescription only (Vulvovaginal candidiasis or Vaginal thrush)	"Miconazole vaginal cream (Gyno-Daktarin) with use of applicator Two applicators (10g) once daily at night for 7 days or one applicator (5g) once daily at night for 14 days\n\nUse of an applicator is not recommended during pregnancy. Latex condoms and diaphragms ca be damaged by vaginal creams and pessaries, extra precautions are advised."
343	Microlite tablets [ 126 Tablets ]	Microlite tablets [ 126 Tablets ]	"MICROLITE\nMicrolite tablets [ 126 Tablets ]\n\nDirections to use : One tablet daily for 21 days."
84	MINULET	MINULET	"MINULET® 75 micrograms/30 micrograms coated tablets The tablets must be taken every day at about the same time, if necessary with a little liquid, in the order shown on the blister pack. One tablet is to be taken daily for 21 consecutive days. Every subsequent blister pack is started after a 7-day tablet-free interval  during which time a withdrawal bleeding usually occurs.  Mitte x 1/12 & Repeat for 6/12.\nFurther instructions are in your Patient Record."
102	Modafinil 200mg to treat sleepiness	Modafinil 200mg to treat sleepiness	Modafinil 200mg P.O, O.D  Dispense 28 (TWENTY EIGHT) tablets.
81	Molaxole laxatives	Molaxole laxatives	Molaxole® Powder for Oral Solution (macrogol 3350/sodium chloride/sodium hydrogen carbonate/potassium chloride) 1-2 sachets to be taken daily 
115	Mometasone furoate nasal spray	Mometasone furoate nasal spray	Mometasone furoate nasal spray 100mcg two sprays in each nostril twice daily for 1 week then reduce to one spray in each nostril for 1 week. x 1/12
160	Movicol Paediatric Plain  Constipation	Movicol Paediatric Plain  Constipation	Movicol Paediatric Plain 6.9 g sachet, 1- 2 sachets per day Dispense 30 sachet. If no improvement in 1 week see your GP.
261	Mycostatin liquid Antifungal	Mycostatin liquid Antifungal	Mycostatin (Nystatin100,000units/ml) Oral Drops. One ml P.O. Q.I.D. x 1
30	Mysimba  starters	Mysimba  starters	"Mysimba 8 mg/90 mg prolonged-release tablets\n\n• Week 1: One tablet in the morning • Week 2: One tablet in the morning and one tablet in the evening • Week 3: Two tablets in the morning and one tablet in the evening • Week 4 and onwards: Two tablets in the morning and two tablets in the evening\n\nMitte 1/12 and repeat 3/12"
29	Mysimba continuation	Mysimba continuation	"Mysimba 8 mg/90 mg prolonged-release tablets Two tablets in the morning and two tablets in the evening\n\nMitte 1/12 and repeat 3/12"
40	Naratriptan 2.5mg Migriane	Naratriptan 2.5mg Migriane	"Naratriptan 2.5mg \n\nOne to be taken at the onset of symptoms  Dispense x 6 tabs. Repeat x 6/12."
54	Naseptin Nasal Cream	Naseptin Nasal Cream	"Naseptin 0.1% & 0.5% w/w Nasal Cream \n\nA small amount of 'Naseptin' is placed on the little finger and applied to the inside of each nostril. Apply 2-4 times a day or as directed for 10 days. Miite x 1 tube"
140	Naseptin Topical Abx	Naseptin Topical Abx	Naseptin Nasal Cream. Q.I.D x 10/7. Dispense 15g tube.
176	Nasocort [Triamcinalone acetonide 55mcg] Nasal spray Steroid	Nasocort [Triamcinalone acetonide 55mcg] Nasal spray Steroid	Nasocort [Triamcinalone acetonide 55mcg] 1 spray per nostril dail  repeat x 6/12
170	Nasofan Aqueous Nasal Spray Allergy	Nasofan Aqueous Nasal Spray Allergy	"Nasofan Aqueous Spray 2 sprays to each nostril mane x 2/52 and then when symptoms are controlled, reduce to 1spray each nostril mane as maintenance x 1/12 and repeat x 6/12.\n\nAlways gargle with water after using this spray"
306	Nasonex Nasal Spray	Nasonex Nasal Spray	"Nasonex Nasal Spray: 2 sprays to each nostril mane x 2/52 and then when symptoms are controlled, reduce to 1 spray each nostril mane as maintenance. x 1/12 and repeat x 6/12.\n\nALWAYS GARGLE WITH WATER AFTER USING THIS NASAL SPRAY. "
151	Nizoral (Ketoconazole) Topical	Nizoral (Ketoconazole) Topical	"Etoflam 5% Cream. T.I.D/P.R.N x 1 tube. Massage well into affected area. \n\n"
345	Noriday tablets [ 168 Tablets ]	Noriday tablets [ 168 Tablets ]	"NORIDAY\nNoriday tablets [ 168 Tablets ]\n\nDirections to use : Take one tablet daily, at the same time every day."
135	Novorapid Insulin Diabetes	Novorapid Insulin Diabetes	"Novorapid Insulin 100units/ml 3ml Cartridges. Dose as per blood glucose readings.\nDispense x 2 Packs (of 5 Cartridges). Repeat x 6"
344	Nuvaring 6 month [ 2 Packs of 3 rings ]	Nuvaring 6 month [ 2 Packs of 3 rings ]	"NUVARING\nNuvaring 6 month [ 2 Packs of 3 rings ]\n\nDirections to use : Insert ring into vagina on day 1 of cycle and leave in for 3 weeks; remove ring on day 22; subsequent courses repeated after 7-day ring-free interval"
242	Ofloxacin  Abx	Ofloxacin  Abx	Ofloxacin 400mg P.O.B.D. x 2/52
154	Oilatum Shower Gel emollient topical	Oilatum Shower Gel emollient topical	"Oilatum Shower Gel 70% w/w Gel.  Dispense 150g. Repeat x 6\n\nUse as a soap substitute."
145	Olmesartan	Olmesartan	Olmesartan 40mg P.O O.D x 1/12 Repeat x 6/12
272	Omeprazole PPI	Omeprazole PPI	Omeprazole  10/20/40 mg P.O. O.D. x 1/12 and repeat x 6/12.
320	Ondasteron (Zofran)	Ondasteron (Zofran)	"Ondasteron 8 mg orally 3 times a day for 5 days.\n\nPlease check your online account for further instructions or read the leaflet"
187	Opatanol eye drops allergic conjunctivitis and allergic rhinitis.	Opatanol eye drops allergic conjunctivitis and allergic rhinitis.	Opatanol eye drops 5 mls 1 drop in the affected eye B.D/P.R.N x 1/12 and repeat x 6/12
60	Ovranette tablets	Ovranette tablets	"OVRANETTE\nOvranette tablets [ 126 Tablets ]\n\nDirections to use : One tablet daily for 21 days.\n\nPlease check your online account for further instructions or read the leaflet"
107	Ovranette tablets	Ovranette tablets	"Ovranette tablets [ 126 Tablets ]\nDirections to use : One tablet daily for 21 days.\n\nFor further instructions please read the leaflet"
348	Ovreena tablets [ 126 Tablets ]	Ovreena tablets [ 126 Tablets ]	"OVREENA\nOvreena tablets [ 126 Tablets ]\n\nDirections to use : One tablet daily for 21 days.\n\nFor further instructions please read the leaflet"
59	Pantoprazole 40mg	Pantoprazole 40mg	"Pantoprazole 40mg, one tablet to be taken in the morning \n\nMiite 1/12 and repeat 6/12"
38	Paxlovid for COVID	Paxlovid for COVID	Paxlovid twice a day for 5 days
249	Phenergan Syrup  (Promethazine) Antihistamine Paediatrics	Phenergan Syrup  (Promethazine) Antihistamine Paediatrics	"Phenergan Syrup  (Promethazine) 5mg/5ml x 100ml\n\nChild 2–4 years\n\n5 mg twice daily, alternatively 5–15 mg once daily, dose to be taken at night.\n\nChild 5–9 years\n\n5–10 mg twice daily, alternatively 10–25 mg once daily, dose to be taken at night.\n\nChild 10–17 years\n\n10–20 mg 2–3 times a day, alternatively 25 mg once daily, dose to be taken at night, increased if necessary to 25 mg twice daily."
259	Phenoxymethylpenicillin  Paediaterics Abx	Phenoxymethylpenicillin  Paediaterics Abx	Phenoxymethylpenicillin 250mg/5ml  SELECT DOSE mg P.O. Q.I.D. x 10/7 days.
260	Phenoxymethylpenicillin Abx	Phenoxymethylpenicillin Abx	Phenoxymethylpenicillin 666mg P.O. Q.I.D. x 5 days.
315	Piriton (Chlorpheniramine) Antihistamine	Piriton (Chlorpheniramine) Antihistamine	"Piriton (Chlorpheniramine) 4mg P.O. Q.I.D/P.R.N Dispense x 30 tabs\n\nThis medicine may cause drowsiness. Avoid Alcohol with this medicine."
257	Ponstan  Analgesia NSAID Menstrual	Ponstan  Analgesia NSAID Menstrual	Ponstan Fort. 1 tab. P.O. T.I.D.  x 3/52 tabs, repeat x 3
189	Pravastatin	Pravastatin	"Pravastatin 40mg tP.O. Nocte. x 1/12 and repeat x 6/12\n"
48	Pred Forte 1% w/v, Eye Drops Suspension	Pred Forte 1% w/v, Eye Drops Suspension	Pred Forte 1% w/v, Eye Drops Suspension One to two drops instilled into the conjunctival sac two to four times daily
205	Prednesol  Steroid Paediatrics	Prednesol  Steroid Paediatrics	Prednesol 5mg Tabs. 20mg P.O. O.D. x 4/7 then reduce to 15mg P.O.O.D. x 3/7 then reduce to 5mg P.O.O.D. x 2/7 and then to 2.5mg P.O.O.D. x 1/7 and then stop.
322	Prednisolone 40mg steroids	Prednisolone 40mg steroids	"Prednisolone 40mg (8*5mg tablets) O.D. (morning) x 5/7.\n\nStop using if causes stomach pain. Avoid prolonged use. "
89	Pregnant women- Recurrent vulvovaginal candidiasis (Thrush)	Pregnant women- Recurrent vulvovaginal candidiasis (Thrush)	"Cloritomazole 200mg pessary once daily for 6 nights.\n\nUse of an applicator is not recommended during pregnancy. Latex condoms and diaphragms ca be damaged by vaginal creams and pessaries, extra precautions are advised.\n"
88	Pregnant women- Vulvovaginal candidiasis (Thrush)	Pregnant women- Vulvovaginal candidiasis (Thrush)	"Cloritomazole 200mg pessary once daily for 3 nights.\n\nUse of an applicator is not recommended during pregnancy. Latex condoms and diaphragms ca be damaged by vaginal creams and pessaries, extra precautions are advised."
47	Preparation H Ointment 25g for hemorrhoids.	Preparation H Ointment 25g for hemorrhoids.	Preparation H rectal Ointment 25g 4 times daily x 1/52
329	Primulut N (Norethisterone)	Primulut N (Norethisterone)	"Primulut N (Norethisterone)\nPrimulut N (Norethisterone) 5mg Tabs. One P.O. T.I.D. Mitte x 9 days’ supply.\n\nDirections to use: Treatment should be started three days before menstruation is likely to begin. After discontinuing these medications, you should have a regular period in 2-3 days.\n\nPlease beware! During the therapy cycle, pregnancy must be avoided. Please be advised that, while the goal is to postpone the period, spotting or heavy bleeding may still occur!"
255	Prochlorperazine Stemetil Antiemetic	Prochlorperazine Stemetil Antiemetic	"Prochlorperazine (Stemetil) tabs 5mg, 1-2 P.R.N/Q.I.D Dispense 20 tablets\navoid driving or operating machinery, this medication can cause drowsiness."
46	Proctosedyl Ointment In the local management of pain, pruritus and inflammation associated with internal or external haemorrhoids, and such haemorrhoidal complications as fissures, proctitis, perianal eczema, and post-operative states.	Proctosedyl Ointment In the local management of pain, pruritus and inflammation associated with internal or external haemorrhoids, and such haemorrhoidal complications as fissures, proctitis, perianal eczema, and post-operative states.	Proctosedyl Ointment Application to external surface or by means of the cannula into the rectum, twice daily and after each bowel movement.  Treatment should last for a week.
166	Proctosedyl suppositories topical  haemorrhoids	Proctosedyl suppositories topical  haemorrhoids	"Proctosedyl suppositories  B.D  x 1/52 repeat x 2. \n\nProctosedyl ointment B.D /P.R.N. Dispense 30g"
162	Promethazine (Phenergan) 25mg tabs. Antihistamine Insomnia	Promethazine (Phenergan) 25mg tabs. Antihistamine Insomnia	Promethazine (Phenergan) 25mg tabs. P.O Nocte. Dispense x 14 tablets.
13	Propranolol	Propranolol	Propranolol 40 mg PO OD 1/12  ,repeat 6/12 
309	Propranolol - Anxiety	Propranolol - Anxiety	"Propranolol 10mg  P.O. O.D. Dispense x 10 tabs\n\nTake one as directed."
39	Pulmicort  nebuliser	Pulmicort  nebuliser	"Pulmicort Respules 1 mg/2ml nebuliser suspension  1 mg twice daily for 5/7\n\nAdults (including elderly): Usually 1 - 2 mg twice daily. In very severe cases, the dosage may be further increased.\n\nChildren of 12 years and older: Dosage as for adults.\n\nChildren of 3 months to 12 years: 0.5 - 1 mg twice daily."
297	Pulmicort (Budesonide) Turbohaler - Inhaler	Pulmicort (Budesonide) Turbohaler - Inhaler	"Pulmicort (Budesonide) Turbohaler 200 mcg. 1 puff B.D.  x 1/12 and repeat x 6/12 \n\nALWAYS GARGLE WITH WATER AFTER USING THIS INHALER."
340	Qlaira tablets [ 168 Tablets ]	Qlaira tablets [ 168 Tablets ]	"QLAIRA\nQlaira tablets [ 168 Tablets ]\n\nDirections to use : One tablet daily in order directed on pack"
274	Quetiapine	Quetiapine	"Quetiapine 25mg P.O. To be taken 1-2 or more hours prior to bedtime. Dispense x 10 tabs.\nAvoid driving or operating machinery as this medicine can cause drowsiness."
228	Rabeprazole PPI	Rabeprazole PPI	Rabeprazole Specify 10 or 20 mg. P.O. O.D. x 1/12 repeat x 6/12.
226	Rectogesic  Haemorrhoids Topical	Rectogesic  Haemorrhoids Topical	Rectogesic (Glyceryl Trinitrate). Apply as directed to the affected area B.D. Dispense 1 30g tube.
90	Recurrent vulvovaginal candidiasis (Thrush)	Recurrent vulvovaginal candidiasis (Thrush)	"Fluconazole 150mg PO Days 1, 4 and 7 then weekly for 6 months.\n\nAvoid fluconazole in pregnancy."
132	Relpax (Eletriptan) Migraine	Relpax (Eletriptan) Migraine	"Relpax (Eletriptan) 40mg. P.O. O.D/P.R.N. Dispense pack of 6 and repeat x 6/12\n\nIf another attack occurs after the initial dose, a second dose  aybe taken after 2 hour interval.\n\nIf there is no response to the initial dose DO NOT administer another dose."
294	Relvar Ellipta Inhaler	Relvar Ellipta Inhaler	"Relvar Ellipta 92/22. 1puff O.D x 1/12 and repeat x 6/12\n\n ALWAYS GARGLE WITH WATER AFTER USING THIS INHALER."
178	Rozex Gel (Metronidazole 0.75%) Rosacea	Rozex Gel (Metronidazole 0.75%) Rosacea	Rozex Gel (Metronidazole 0.75%). Apply to clean dry skin B.D. Repeat x 3/12
300	Salamol Inhaler	Salamol Inhaler	"Salamol Easi Breathe Inhaler 100mcg 1-2 puffs P.R.N O.P.x 1 and repeat x 2 \n\nTHIS INHALER SHOULD NOT BE USED FOR REGULAR MAINTENANCE THERAPY. MORE THAN ONCE WEEKLY USEAGE INDICATES POOR ASTHMA CONTROL."
32	Salamol Steri-Neb 5 mg/2.5 ml Nebuliser Solution salbutamol (as sulfate)	Salamol Steri-Neb 5 mg/2.5 ml Nebuliser Solution salbutamol (as sulfate)	"Salamol Steri-Neb 5 mg/2.5 ml Nebuliser Solution salbutamol (as sulfate)\n\nThe recommended dose is:\n\nAdults (including elderly) and adolescents aged 12 years and over:\n\nThe starting dose is 2.5 mg taken by wet inhalation. Your doctor may increase this to 5 mg. Treatment may be repeated up to four times a day. The maximum daily dose is normally 20 mg per day.\n\nFor treatment of severe airways obstruction, the maximum dose of 40 mg per day can only be given under strict medical supervision in hospital.\n\nChildren aged 4 to 11 years:\n\nThe starting dose is 2.5 mg taken by wet inhalation. Their doctor may increase this to 5 mg. Treatment may be repeated up to four times a day.  Children should be supervised by a responsible adult when they are using a nebuliser.\n\nChildren under 4 years of age:\n\nOther pharmaceutical forms may be more appropriate for children under 4 years. Method of administration Salamol Steri-Neb MUST be used by inhalation only and breathed in through the mouth. The solution MUST NOT be injected or swallowed."
31	Saline Steri-Neb 0.9% w/v Nebuliser Solution	Saline Steri-Neb 0.9% w/v Nebuliser Solution	Saline Steri-Neb 0.9% w/v Nebuliser Solution
105	Saxenda First time user prescription	Saxenda First time user prescription	"Saxenda 6 mg/ml solution for injection in pre-filled pen x 5 (1 ml of solution contains 6 mg of liraglutide*. One pre-filled pen contains 18 mg liraglutide in 3 ml.). \n\nPlease also dispense include100 needles along with Saxenda pen.\n\nDose escalation schedule:\n\n0.6mg daily for one week and increase by 0.6mg each week until you reach your maintenance dose which is usually 3mg\nOn maintenance dose of 3mg, each pen will last 6 days"
112	Saxenda repeat prescription	Saxenda repeat prescription	"Saxenda 6 mg/ml solution for injection in pre-filled pen x 5 (1 ml of solution contains 6 mg of liraglutide*. One pre-filled pen contains 18 mg liraglutide in 3 ml.). A maintenance dose of 3mg to be injected as directed daily. \n\nOn maintenance dose of 3mg\n\nPlease also dispense include100 needles along with Saxenda pen"
227	Scheriproct  Suppositories Topical Haemorrhoids	Scheriproct  Suppositories Topical Haemorrhoids	"Scheriproct  Suppositories. One P.R. O.D. as directed. Dispense 1 box suppositories..\n\nScheriproct Ointment Use as directed on the affected area. 30gram tube."
148	Selsun Shampoo 2.5% w/v.	Selsun Shampoo 2.5% w/v.	"Selsun Shampoo 2.5% w/v. Dispense x 100ml. Repeat x 3\n\nMassage Selsun and  rinse after 2 to 3 minutes.  Use twice a week for the first two weeks and then once a week for the next two weeks to control the condition. "
9	Semaglutide for weight loss Weeks 1-4	Semaglutide for weight loss Weeks 1-4	Semaglutide prefilled injection 0.25mg weekly into tummy, thigh or upper arm for 4 weeks
6	Semaglutide for weight loss Weeks 13-16	Semaglutide for weight loss Weeks 13-16	Semaglutide prefilled injection 1.7 mg weekly into tummy, thigh or upper arm for 4 weeks
5	Semaglutide for weight loss Weeks 17 onwards	Semaglutide for weight loss Weeks 17 onwards	Semaglutide prefilled injection 2mg or 2.4mg weekly into tummy, thigh or upper arm for 4 weeks
8	Semaglutide for weight loss Weeks 5-8	Semaglutide for weight loss Weeks 5-8	Semaglutide prefilled injection 0.5mg weekly into tummy, thigh or upper arm for 4 weeks
7	Semaglutide for weight loss Weeks 9-12	Semaglutide for weight loss Weeks 9-12	Semaglutide prefilled injection 1 mg weekly into tummy, thigh or upper arm for 4 weeks
314	Serc (Betahistine Dihydrochloride)	Serc (Betahistine Dihydrochloride)	Serc (Betahistine Dihydrochloride) 16mg P.O. T.I.D x 1/52 Repeat x 2
301	Seretide + Ventolin Inhaler	Seretide + Ventolin Inhaler	"1. Seretide 250 mcg.  2 puffs B.D x 1/12 and repeat for 6/12\n\nALWAYS GARGLE WITH WATER AFTER USING THIS INHALER. \n\n\n\n2. Salbutamol/Ventolin Inhaler. 100mcg 1 puffs P.R.N O.P.x 1 and repeat x 2 \n\nTHIS INHALER SHOULD NOT BE USED FOR REGULAR MAINTENANCE THERAPY. MORE THAN ONCE WEEKLY USEAGE INDICATES POOR ASTHMA CONTROL."
106	Seretide 125mcg Boosting with Ventolin	Seretide 125mcg Boosting with Ventolin	"Seretide 125mcg.  Boost to 3 doses three times a day for a week, then reduce to 3 doses twice a day the second week and then two doses twice a day for the third week and then back to one dose twice a day as maintenance therapy. . ALWAYS GARGLE WITH WATER AFTER USING THIS INHALER. Mitte  x 1/12 and repeat 6/12\n\nVentolin/Salbutamol inhaler 100 mcg. 1-2 puffs PRN  Mitte x 1/12. Repeat x Once ONLY. This is a rescue inhaler. Regular daily use of this inhaler indicates inadequate control of asthma and medical review is advised. A steroid inhaler should be used instead."
17	Seretide Diskus 250mcg  And Ventollin	Seretide Diskus 250mcg  And Ventollin	"1.  Seretide Diskus 250mcg 1 puff B.D. 1/12 and repeat 6/12.\n\nALWAYS GARGLE WITH WATER AFTER USING THIS INHALER. \n\n2.  Salbutamol/Ventolin Inhaler. 100mcg 1 puffs P.R.N O.P.x 1 and repeat x 2 "
299	Seretide Diskus Ventolin Inhaler	Seretide Diskus Ventolin Inhaler	"1. Seretide Diskus 100mcg 1 puff B.D. x 1/12 and repeat 6/12\n\nALWAYS GARGLE WITH WATER AFTER USING THIS INHALER.\n\n\n\n2. Salbutamol/Ventolin Inhaler 100mcg 1 puffs P.R.N O.P.x 1 and repeat x 2 \n\nTHIS INHALER SHOULD NOT BE USED FOR REGULAR MAINTENANCE THERAPY. MORE THAN ONCE WEEKLY USEAGE INDICATES POOR ASTHMA CONTROL."
298	Seretide Evohaler - Inhaler	Seretide Evohaler - Inhaler	"Seretide 125 Evohaler  2 puffs B.D. x 1/12and repeat 6/12. \n\nALWAYS GARGLE WITH WATER AFTER USING THIS INHALER. "
1	Seretide Evohaler 125 mcg	Seretide Evohaler	125mcg  1 puff B.D. 1/12 and repeat 6/12.
308	Sertraline Antidepressant	Sertraline Antidepressant	Sertraline 50mg P.O. O.D.  x 1/12 and repeat x 6/12
331	SIDENA (GENERIC VIAGRA) 25/50/100mg Erectile Dysfunction	SIDENA (GENERIC VIAGRA) 25/50/100mg Erectile Dysfunction	"SIDENA (GENERIC VIAGRA) 25/50/100mg\nViagra/Sildenafil (Sidena or equivalent) 25/50/100mg tables. P.O. 4 tablets x 6 [ 24 (maximum) tablets ]\n\n1 hour prior to sexual activity to a maximum 1 tablet in any 24 hours.\nFor further instructions please read the leaflet"
188	Silcock's Base Topical	Silcock's Base Topical	 Silcock's Base Use as a soap for cleansing and also as a moisturiser. Dispense 500g tub.
336	SILDENAFIL CLONMEL (GENERIC VIAGRA) 25/50/100mg Erectile Dysfunction	SILDENAFIL CLONMEL (GENERIC VIAGRA) 25/50/100mg Erectile Dysfunction	"SILDENAFIL CLONMEL (GENERIC VIAGRA) 25/50/100mg\nSildenafil 25/50/100mg 4 tablets x 6 [ 24 (maximum) tablets ]\n\nPlease check your online account for further instructions or read the leaflet"
269	Singulair Montelukast	Singulair Montelukast	"Singulair (Montelukast) 10mgs 1 nocte P.O  x1/12 repeat x 6/12. \n"
276	Sinusitis Treatment Abx Nasal spray	Sinusitis Treatment Abx Nasal spray	"1. Doxycycline 100mg P.O B.D x 5/7\n\n2. Avamys Fluticasone Fuorate 27.5mcg Nasal Spray 2 sprays in each nostril twice daily until symptoms are controlled and then reduce to one spray to each nostril mane as maintenance. x 1/12 \n\nALWAYS GARGLE WITH WATER AFTER USING THIS NASAL SPRAY."
179	Skinoren (Azelaic acid 15%) Acne	Skinoren (Azelaic acid 15%) Acne	"Skinoren (Azelaic acid 15%). Apply BD to affected areas. Repeat x 6/12\n\n"
80	SNRI - Venlablue XL 150mg	SNRI - Venlablue XL 150mg	"Venlablue XL 150mg, one tablet to be taken daily. 1/12 and repeat 6/12\n"
79	SNRI Venlablue XL 75mg	SNRI Venlablue XL 75mg	"Venlablue XL 75mg, one tablet to be taken daily. 1/12 and repeat 6/12\n\n"
216	Sofradex Ear Drops Abx Steroid	Sofradex Ear Drops Abx Steroid	"Sofradex Ear Drops  2-3 drops into the affected ear(s) T.I.D x 1/52\n"
53	Sofradex Eye Drops	Sofradex Eye Drops	"Sofradex Eye Drops (Framycetin Sulphate 0.5 %w/v (5mg/ml), Gramicidin 0.005% w/v (0.05 mg/ml), Dexamethasone sodium metasulphobenzoate equivalent to Dexamethasone 0.05% w/v (0.5 mg/ml).\n\nOne or two drops applied to each affected eye up to six times daily or more frequently if required x maximum 7 days or less if the issue is resolved."
76	Solpadeine 15mg/500mg	Solpadeine 15mg/500mg	Solpadeine 15mg/500mg PO QDS x 2.52
56	Soolantra	Soolantra	"Soolantra 10 mg/g cream ivermectin to be applied to the affected are of the FACE only. Miite 1/12 and repeat 3/12\n\nOne application on facial skin per day. Apply a pea size amount of the cream to each of the five areas of the face: forehead, chin, nose and each cheek. Then spread the cream as a thin layer across the entire face\n\nOnly for use on the skin of the face. Do not use this medicine on other parts of your body, especially not moist body surfaces, e.g. your eyes, your mouth or any mucosa.\n\nStieprox® 15 mg/g Shampoo (ciclopirox olamine) to be applied to the affected area 2-3 times a week for a total of 4 weeks.\n\nSee your online account for more details."
173	Soolantra  ivermectin cream Topical	Soolantra  ivermectin cream Topical	 Soolantra Cream 30g Apply once daily to entire face in thin film. Wash hands carefully after use. Dispense 1 tube and repeat x 3
332	SPEDRA 50/100/200MG	SPEDRA 50/100/200MG	"SPEDRA 50/100/200MG\nSpedra 50/100/200 mg tablets. P.O. 4 tablets x 6 [ 24 (maximum) tablets]\n\n15-30 mins prior to sexual activity to a max. of 1 tablet in any 24 hours.\n\nFor further instructions please read the leaflet"
270	Spedra Avanafil  Erectile dysfunction ED	Spedra Avanafil  Erectile dysfunction ED	"Spedra (Avanafil) 100mg  P.O. 1 box x 4 tablets. Repeat x 6 boxes.\n\n15-30 mins prior to sexual activity to a max. of 1 tablet in any 24 hours."
307	Sterimar Nasal Spray	Sterimar Nasal Spray	"Sterimar Nasal Spray: 1 spray to each nostril P.R.N x 1& repeat x 6/12\nIf  used with a steroid nasal spray, use the Sterimar spray 5-10 minutes prior to using the steroid nasal spray."
3	Stieprox 15 mg/g Shampoo for dandruff and seborrhoeic dermatitis (above 12 years old)	Stieprox 15 mg/g Shampoo for dandruff and seborrhoeic dermatitis (above 12 years old)	"Stieprox 15 mg/g Shampoo ciclopirox olamine. Use Stieprox two to three times a week for upto 4 weeks.\n\nHow to apply Stieprox 1. Wet your hair. 2. Use enough Stieprox so that the lather covers your scalp, hair and adjacent areas, if affected. 3. Massage the scalp and adjacent areas, if needed, really well using your fingertips. 4. Rinse your scalp and hair thoroughly. 5. Repeat steps 2 to 4."
57	Stieprox® 15 mg/g Shampoo for scalp	Stieprox® 15 mg/g Shampoo for scalp	"Stieprox® 15 mg/g Shampoo (ciclopirox olamine) to be applied to the affected area 2-3 times a week for a total of 4 weeks.\n\nSee your online account for more details."
85	Sumatriptan tablets (Imigran/ Sumatran) - 100mg	Sumatriptan tablets (Imigran/ Sumatran) - 100mg	"Sumatriptan tablets (Imigran/ Sumatran) - 100mg\n\nOne to be taken at the onset of symptoms and repeat after 2 hours if symptoms are not settling. Dispense x 6 tabs. Repeat x 6/12."
304	Symbicort + Salbutamol Inhaler	Symbicort + Salbutamol Inhaler	"1. Symbicort Turbohaler 200/6mcg 1 puff twice daily x 1/12  and repeat x 6/12\n\nALWAYS GARGLE WITH WATER AFTER USING THIS INHALER.\n\n\n2.Salbutamol/Ventolin Inhaler 100mcg 1 puffs P.R.N O.P.x 1 and repeat x 2 \n\nTHIS INHALER SHOULD NOT BE USED FOR REGULAR MAINTENANCE THERAPY. MORE THAN ONCE WEEKLY USEAGE INDICATES POOR ASTHMA CONTROL."
118	Symbicort Turbohaler: 100/6 booster and Vetollin	Symbicort Turbohaler: 100/6 booster and Vetollin	"Symbicort Turbohaler: 100/6: two puffs three times daily for two weeks, two puffs in the morning and evening for two weeks, and then one puff in the morning and evening as maintenance therapy. GAG WITH WATER AFTER USING THIS INHALER AT ALL TIMES. repeat six times, starting in the middle.\nSalbutamol/Ventolin Inhaler. 100mcg 1 puffs P.R.N O.P.x 1 and repeat x 2 \n\nTHIS INHALER SHOULD NOT BE USED FOR REGULAR MAINTENANCE THERAPY. MORE THAN ONCE WEEKLY USEAGE INDICATES POOR ASTHMA CONTROL."
19	Symbicort Turbohaler: 400/12 mcg and Salbutamol/Ventolin Inhaler	Symbicort Turbohaler: 400/12 mcg and Salbutamol/Ventolin Inhaler	"Symbicort Turbohaler: 400/12 mcg  two puffs twice a day x 1/12 and repeat 6/12\n\nGAG WITH WATER AFTER USING THIS INHALER AT ALL TIMES\n\nSalbutamol/Ventolin Inhaler 100mcg 1-2  puffs as required x 1 and repeat x 2 \n\nTHIS INHALER SHOULD NOT BE USED FOR REGULAR MAINTENANCE THERAPY. MORE THAN ONCE WEEKLY USEAGE INDICATES POOR ASTHMA CONTROL."
144	Tears Naturale eye drops	Tears Naturale eye drops	Tears Naturale eye drops, solution (Dextran 70 0.1% w/v, Hypromellose 0.3% w/v). 1-2 drops P.R.N, Dispense 1 x 15ml. Repeat x 3.
248	Telfast Fexofenadine Antihsitamine	Telfast Fexofenadine Antihsitamine	Telfast (Fexofenadine) Specify dose: 120 or 180mg: One P.O.O.D. x 30 repeat 6/12
263	Terbinafine Antifungal	Terbinafine Antifungal	"Terbinafine 250mg P.O. O.D. x 1/12 repeat for 6/12\n"
70	Terbinafine antifungal (Tinea	Terbinafine antifungal (Tinea	Terbinafine cream Topical 1%. To be applied to the affected area 1-2x/daily for 1 week.
264	Terbinafine Cream Antifungal Topical	Terbinafine Cream Antifungal Topical	"Terbinafine Cream x 30g and repeat x 6 times.\n\nMassage into the skin of both feet twice a day for at least a month. Repeat for a further two months if required."
110	Tetralysal/Lymecycline 300mg	Tetralysal/Lymecycline 300mg	"Tetralysal/Lymecycline 300mg P.O O.D x 3/12\n\nUse SPF and avoid strong sun exposure. Avoid pregnancy while using this medication. Take with a glass of water or food"
181	Tetralysal/Lymecycline Acne Abx	Tetralysal/Lymecycline Acne Abx	"Tetralysal/Lymecycline 300mg P.O O.D x 3/12\n\nUse SPF and avoid strong sun exposure. Avoid pregnancy while using this medication. Take with a glass of water or food"
141	Thwart topical wart	Thwart topical wart	Thwart 26% w/w Cutaneous Solution. O.D until warts disappear or maximum of 6 weeks . Dispense 10mls.
267	Tibolone HRT	Tibolone HRT	"Tibolone 2.5mg P.O. O.D. x 1/12 repeat 6/12\n"
45	Tizanidine 2 mg Tablets MUSCLE SPASM, RELAXANT	Tizanidine 2 mg Tablets MUSCLE SPASM, RELAXANT	"Tizanidine 2 mg Tablets, one tablet twice a day (every 12 hours) for 5 days\n\nFOR DOCTORS! Single doses of Tizanidine should not exceed 12mg and the total daily dose should not exceed 36 mg,"
14	Topiramate 25 mg for migraine	Topiramate 25 mg for migraine	Topiramate 25 mg PO – Take 1 pill at bedtime, once a day 1/12 and repeat 2/12
159	Tranexamic Acid menorrhagia	Tranexamic Acid menorrhagia	"Tranexamic Acid 500mg  2-3 tablets T.I.D, Dispense x 50 tablets. Repeat x 2\n\nStart after heavy bleeding has started for maximum of 4 days"
25	Travel Vaccine (Hep A) Harvix for adults	Travel Vaccine (Hep A) Harvix for adults	"Havrix Monodose Vaccine. (Hepatitis A Vaccine (inactivated, adsorbed), 1440 ELISA units/ 1ml Suspension for injection in a pre-filled syringe)\n\nPrimary immunisation consists of a single dose of Havrix Monodose Vaccine given intramuscularly.\n\nx Mitte single dose"
24	Travel Vaccine (Hep A) Harvix for Children/adolescents (1-15 years)	Travel Vaccine (Hep A) Harvix for Children/adolescents (1-15 years)	"Havrix Junior Monodose Vaccine. (Hepatitis A Vaccine (Inactivated, Adsorbed). 720 ELISA units/ 0.5ml Suspension for injection in a pre-filled syringe)\n\nPrimary immunisation consists of a single dose of Havrix Junior Monodose vaccine (720 ELISA units/0.5 ml) given intramuscularly.\n\nx Mitte single dose"
26	Travel vaccine REVAXIS Suspension for injection in pre-filled syringe Diphtheria, tetanus and poliomyelitis (inactivated) vaccine (adsorbed, reduced antigen(s) content)	Travel vaccine REVAXIS Suspension for injection in pre-filled syringe Diphtheria, tetanus and poliomyelitis (inactivated) vaccine (adsorbed, reduced antigen(s) content)	"REVAXIS Suspension for injection in pre-filled syringe  Dosage: 0.5 ml.\n\nDiphtheria, tetanus and poliomyelitis vaccine\n\nFor intramuscular injection only. The recommended injection site is the deltoid region. REVAXIS must not be administered by intradermal or intravascular routes."
218	Travocort Cream Antifungal Topical	Travocort Cream Antifungal Topical	Travocort (Isoconazole/ Difluocortolone) Cream B.I.D. x 1/52 then reduce to Nocte x 1/52 and then alternate nights x 1/52 and then stop. Apply sparingly to the affected areas and avoid prolonged continuous use.
290	Trimethoprim Abx	Trimethoprim Abx	"Trimethoprim 200mg P.O. B.D.  x 3 days. \n\nAvoid pregnancy when taking this medicine."
289	Trimethoprim Paediatric Abx	Trimethoprim Paediatric Abx	"Trimethoprim 10mg/ml oral solution. PO. CHOOSE mg BD for 3 days.\n"
163	Ultraproct ointment Topical  Haemorrhoids	Ultraproct ointment Topical  Haemorrhoids	"Ultraproct ointment B.D after bowel movement as directed  up to 7 days\n\n"
324	UTI/Cystitis Macrobid (Nitrofurantoin MR) Abx	UTI/Cystitis Macrobid (Nitrofurantoin MR) Abx	Macrobid (Nitrofurantoin MR) 100mg caps. One P.O. B.D. C.C. Mitte x 3/7(If Macrobid is not available, then use Macrodantin [Nitrofurantoin SR) 50mg Q.I.D. Mitte x 3/7 instead)
147	Vagifem HRT PV	Vagifem HRT PV	"Vagifem 10 micrograms vaginal tablets. Dispense 24 vaginal tablets with applicators. \n\nInitial dose: One vaginal tablet nocte for two weeks. Maintenance dose: One vaginal tablet twice a week."
283	Valtrex Valaciclovir 500mg Antiviral	Valtrex Valaciclovir 500mg Antiviral	Valtrex/Valaciclovir 500mg P.O. B.D.  for 5 days. Dispense x 10 tabs. Repeat x 4
282	Valtrex Valaciclovir Antiviral For suppression of recurrences	Valtrex Valaciclovir Antiviral For suppression of recurrences	"Valtrex/Valaciclovir 250mg B.D PO. Pack of 60. Repeat * 2\nTreatment should be re-evaluated after 6 months of therapy."
281	Valtrex Valaciclovir Antiviral Genital Herpes	Valtrex Valaciclovir Antiviral Genital Herpes	Valtrex/Valaciclovir 500mg P.O. B.D. x 5/7 days. Dispense x 10 tabs. Repeat x 4
171	VANIQA 11.5% CREAM - hirsutism	VANIQA 11.5% CREAM - hirsutism	"VANIQA 11.5% CREAM. 30g per month. B.D to affected area, Dispense x 3 60g tubes for 6-month supply.\n\nApply Vaniqa cream to the affected area twice daily, at least eight hours apart. If no improvement after 4 months, discontinue.\n\nAvoid pregnancy & breast feeding when using this product."
33	Ventolin Nebules 5mg/2.5ml Nebuliser Solution	Ventolin Nebules 5mg/2.5ml Nebuliser Solution	"Ventolin Nebules 5mg/2.5ml Nebuliser Solution \n\nAdults and adolescents aged 12 years and over: A suitable starting dose of salbutamol by wet inhalation is 2.5 milligrams. This may be increased to 5 milligrams. Treatment may be repeated up to four times daily. In adult dosing, up to 40 milligrams per day, can be given under strict medical supervision in hospital for the treatment of severe airways obstruction.\n\nPaediatric population For children aged 4 to 11 years: A suitable starting dose of salbutamol by wet inhalation is 2.5 milligrams.  This may be increased to 5 milligrams. Treatment may be repeated up to four times daily.\n\nOther pharmaceutical forms may be more appropriate for administration in children under 4 years old."
305	Ventolin Salbutamol Inhaler	Ventolin Salbutamol Inhaler	"Salbutamol/Ventolin Inhaler. 100mcg 1 puffs P.R.N O.P.x 1 and repeat x 2 \n\nTHIS INHALER SHOULD NOT BE USED FOR REGULAR MAINTENANCE THERAPY. MORE THAN ONCE WEEKLY USEAGE INDICATES POOR ASTHMA CONTROL."
327	Ventollin and Becotide Inhaler	Ventollin and Becotide Inhaler	"1.  Becotide 100 mcg inhaler  1 puff B.D. 1/12 and repeat 6/12.\n\nALWAYS GARGLE WITH WATER AFTER USING THIS INHALER.\n\n\n\n2.  Salbutamol/Ventolin Inhaler. 100mcg 1 puffs P.R.N O.P.x 1 and repeat x 2 \n\nTHIS INHALER SHOULD NOT BE USED FOR REGULAR MAINTENANCE THERAPY. MORE THAN ONCE WEEKLY USEAGE INDICATES POOR ASTHMA CONTROL."
75	Versatis® 5% medicated plaster (lidocaine)	Versatis® 5% medicated plaster (lidocaine)	"Versatis® 5% medicated plaster (lidocaine) to be applied topically to the affected area x 1/52\n\nThe usual daily dose is to use between one and three plasters of the size of the painful areas of your skin. Versatis may be cut into smaller pieces to fit the affected area. You should not use more than 3 plasters at the same time. The plasters should be removed after 12 hours of use, so that you have a 12 hour period with no plaster."
335	VIAGRA 25/50/100mg Erectile Dysfunction	VIAGRA 25/50/100mg Erectile Dysfunction	"VIAGRA 25/50/100mg\nViagra 25/50/100mg 4 tablets x 6 [ 24 (maximum) tablets ]\n\nFor further instructions please read the leaflet"
197	Vibramycin/Doxycycline Malaria Prophylaxis	Vibramycin/Doxycycline Malaria Prophylaxis	"Vibramycin/Doxycycline 100mg Caps. One P.O. O.D.  x  (SPECIFY NO OF DAYS OF TREATMENT) caps.\n\nAdvice for patients\n\nStart the tablets 24 hours prior to entering malaria zone and continue for the duration of your stay and for 28 days after leaving the danger area.\nAvoid pregnancy and breastfeeding when taking this medicine. "
128	Vimovo NSAID PPI Analgesia	Vimovo NSAID PPI Analgesia	Vimovo 500/20mg x 1/52, one tablet to be taken every 12 hours fpr one week and repeat x 2
16	Violite tablets	Violite tablets	"Violite tablets [ 126 Tablets ]\nDirections to use : One tablet daily for 21 days.\n\nPlease check your online account for further instructions or read the leaflet"
321	Viral gastroentritis	Viral gastroentritis	"Imodium 2mg PO OD QDS 5/7\n\nMetaclopromide 10mg PO TDS 5/7\n\nBuscopan 10mg TDS PO for 5/7"
95	Vulvovaginal candidiasis or Vaginal thrush	Vulvovaginal candidiasis or Vaginal thrush	"Cloritomazole (Canestan) 500mg pessary Single dose\n\nInsert the pessary using applicator. Use of an applicator is not recommended during pregnancy. Latex condoms and diaphragms ca be damaged by vaginal creams and pessaries, extra precautions are advised."
190	Warticon Cream Podophyllotoxin Topical	Warticon Cream Podophyllotoxin Topical	Warticon Cream. B.D for 3 days, do not apply for next 4 days. Restart cycles until warts disappear.  Dispense 1 tube x 1 repeat.
349	Xenical (Orlistat) 120mg [252 capsules, 12 week course] [ 252 Capsules ]	Xenical (Orlistat) 120mg [252 capsules, 12 week course] [ 252 Capsules ]	"Xenical (Orlistat) 120mg [252 capsules, 12 week course] [ 252 Capsules ]\nDosage:\n\nTake one capsule with water three times a day immediately before, during or up to an hour after each main meal.\n\nFor further instructions please read the leaflet"
251	Xyzal Levocetirizine Antihistamine	Xyzal Levocetirizine Antihistamine	Xyzal (Levocetirizine) 5mg. P.O. O.D. x 1/12, repeat 6/12
326	Yasmin	Yasmin	"Yasmin (0.030 mg ethinylestradiol and 3 mg drospirenone)\nThe tablets must be taken every day at about the same time, if necessary with a little liquid, in the order shown on the blister pack. One tablet is to be taken daily for 21 consecutive days. Every subsequent blister pack is started after a 7-day tablet-free interval  during which time a withdrawal bleeding usually occurs.  Mitte x 1/12 & Repeat for 6/12.\nFurther instructions are in your Patient Record."
337	Yasminelle tablets [ 126 Tablets ]	Yasminelle tablets [ 126 Tablets ]	"YASMINELLE\nYasminelle tablets [ 126 Tablets ]\n\nDirections to use : One tablet daily for 21 days. Further instructions are in your Patient Record."
116	Yaz	Yaz	"YAZ\nYaz tablets [ 168 Tablets ]\n\nDirections to use : One tablet daily for 28 days."
172	Zindaclin  Abx Topical Acne	Zindaclin  Abx Topical Acne	Zindaclin 1%  30g Apply thin film daily for no longer than 3 months. Dispense 1 tube and repeat x 3
10	Zineryt® 40mg/12mg For Acne	Zineryt® 40mg/12mg For Acne	"Zineryt® 40mg/12mg per ml Powder and Solvent for Cutaneous Solution (erythromycin and zinc acetate dihydrate) 1/12 and repeat 3/12\n\nshould be applied all over the affected area and the surrounding skin twice a day "
109	Zoely	Zoely	"Zoely tablets [ 168 Tablets ]\n\nDirections to use: One tablet daily for 24 days, followed by i inactive tablet daily for 4 days; subsequent courses repeated without interval.\n\nPlease check your online account for further instructions or read the leaflet."
208	Zomig Rapimelt Migraine	Zomig Rapimelt Migraine	Zomig Rapimelt Tabs. One to be taken at the onset of symptoms and repeat after 2 hours if symptoms are not settling. Dispense x 6 tabs. Repeat x 6/12.
280	Zovirax Aciclovir Antiviral	Zovirax Aciclovir Antiviral	"Zovirax/Aciclovir 200mg PO T.I.D x 5/7 days.\n"
278	Zovirax Aciclovir Antiviral Genital Herpes	Zovirax Aciclovir Antiviral Genital Herpes	"Zovirax Aciclovir 400mg PO T.I.D x 5/7 days.\n"
235	Zovirax Suspension Paediatrics Antiviral	Zovirax Suspension Paediatrics Antiviral	"Zovirax Suspension: Specify strength and age: 200mg/5ml or 400mg /5ml.\n\nDosing: age <2>\n\n2-6 years: 400mg  Q.I.D.\n\n>6 years: 800mg Q.I.D. \n\nSpecify quantity to be dispensed 125ml or 100ml (Double strength)"
316	Zyban 150 mg prolonged release tablets. smoking cessation	Zyban 150 mg prolonged release tablets. smoking cessation	"Zyban 150 mg prolonged release tablets. The initial dose is 150 mg to be taken daily for six days, increasing on day seven to 150 mg twice daily. Mitte * 120 tablets. Started while still smoking and a target stop date set within the first two weeks of treatment, preferably in the second week.  There should be an interval of at least 8 hours between doses. If at seven weeks no effect is seen, treatment should be discontinued. \n\nFor further instructions please read the leaflet"
EOD;

$lines = explode("\n", $rawData);
$drugs = [];
foreach ($lines as $line) {
    if (empty(trim($line))) continue;
    
    $parts = explode("\t", $line);
    if (count($parts) >= 4) {
        $drugs[] = [
            'num' => $parts[0],
            'name' => trim($parts[1]),
            'line1' => trim(trim($parts[2], '"')),
            'desc' => trim(trim($parts[3], '"'))
        ];
    }
}

echo json_encode($drugs, JSON_PRETTY_PRINT);
